
function Footer() {

    const currentYear = new Date().getFullYear()
    return (
        <footer className="max-width flex col">
            <span className="spacer-1"></span>
            <p className="spacer-1">All info and images were generated by ChatGPT or taken from TMDB Api</p>

            <hr className="spacer-1"/>
            <p className="spacer-1">Made by Andrii Oleniuk | {currentYear}</p>
        </footer>
    )
}

export default Footer
